FROM --platform=linux/amd64 node:16.17.0 as build

WORKDIR /code

COPY package.json package.json
COPY package-lock.json package-lock.json


RUN npm ci --production

COPY . .

RUN npm run build

# NGINX Web Server
#loosly coupled highly cohesive, separation of concerns
FROM nginx:1.22.0-alpine as prod

COPY --from=build /code/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]









